#!/bin/bash
# Debugging-Anleitung für Admin-Status

echo "📋 Admin-Status Debug-Guide"
echo "==========================="
echo ""
echo "1. Öffne Browser DevTools (F12)"
echo ""
echo "2. Suche in der Console nach diesen Logs:"
echo "   ✅ 🔐 [ADMIN-CHECK] - Zeigt ob Admin erkannt wurde"
echo "   ✅ 👑 [ADMIN-STATUS] - Bestätigung ob Admin oder User"
echo "   ✅ 💾 [STORAGE] - Was im localStorage gespeichert wurde"
echo ""
echo "3. Überprüfe localStorage:"
echo "   → F12 → Application/Speicher → Local Storage"
echo "   Dort sollte stehen:"
echo "     - is_group_admin: 'true' (wenn Admin)"
echo "     - admin_pubkey: 'abc123...'"
echo "     - group_secret: 'group-secret...'"
echo ""
echo "4. Wenn Admin erkannt:"
echo "   → Der Button '🔐 Whitelist verwalten' sollte sichtbar sein"
echo "   → Klick darauf, um zur Admin-Seite zu gehen"
echo ""
echo "5. Troubleshooting:"
echo ""
echo "   ❌ Button nicht sichtbar?"
echo "   → Überprüfe: localStorage hat is_group_admin = 'true'"
echo "   → Überprüfe: admin_pubkey === userStore.pubkey"
echo ""
echo "   ❌ Admin-Status nicht richtig erkannt?"
echo "   → Schau in Console nach [ADMIN-CHECK] log"
echo "   → Vergleiche adminPubkey mit userPubkey"
echo ""
echo "   ❌ Whitelist-Seite zeigt 'Nur Admin kann hier rein'?"
echo "   → Überprüfe localStorage nochmal"
echo "   → Browser-Cache leeren (Strg+Shift+Delete)"
echo ""
